FROM thecodingmachine/php:7.2-v4-apache

# ... (your other configurations)

# Change back Apache user and group to www-data
ENV APACHE_RUN_USER=www-data \
    APACHE_RUN_GROUP=www-data

# Copy the application files
COPY . /var/www/html/


RUN composer install
