# fly.toml app configuration file generated for codecry on 2023-10-10T00:06:22+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "sin"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
